//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningPlanner.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WoodenHuskyJazzEntities : DbContext
    {
        public WoodenHuskyJazzEntities()
            : base("name=WoodenHuskyJazzEntities")
        {
        }

        public WoodenHuskyJazzEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chains> Chains { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialsChains> MaterialsChains { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TimeZones> TimeZones { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
