//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningPlanner.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsChains
    {
        public int MaterialsID { get; set; }
        public short ChainsID { get; set; }
        public byte MaterialsPosition { get; set; }
        public byte Progress { get; set; }
        public byte StatusID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Chains Chains { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
