CREATE TABLE [dbo].[Priority] (
    [ID]   TINYINT       IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Priority] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UC_Priority_Name] UNIQUE NONCLUSTERED ([Name] ASC)
);

